### ISSUE TITLE
Can't find the path of the Inkscape executable.

### ISSUE THREAD

**Issue by MaitrePo** [brad/Inkscape-OpenSCAD-DXF-Export#21]
Hello,

I just installed Inkscape and your OpenSCAD-DXF-export extension on Windows 10, but when I try to use it, I get the following error message : 

> Traceback (most recent call last):
  File "openscad_dxf.py", line 287, in <module>
    OpenSCADDXFEffect().affect()
  File "openscad_dxf.py", line 48, in __init__
    object2path.ObjectToPath.__init__(self)
  File "C:\Users\Pauline\AppData\Roaming\inkscape\extensions\openscad_dxf\inkinkex.py", line 73, in __init__
    self.inkscape_path = inkutils.find_inkscape_path()
  File "C:\Users\Pauline\AppData\Roaming\inkscape\extensions\openscad_dxf\inkutils.py", line 25, in find_inkscape_path
    raise InkscapeEnvironmentError(
inkutils.InkscapeEnvironmentError: Can't find the path of the Inkscape executable.

When I installed Inkscape, I choose to add it in the path for all uers.
I put the file and the directory under :  
C:\Users\Pauline\AppData\Roaming\inkscape\extensions
and
C:\Program Files\Inkscape\share\inkscape\extensions\

I tried to move the content of the openscad_dxf directory at the same place than openscad_dxf.inx, in both places (Users and Program Files) but I still get the error, OR the OpenDXF export format is not available. 
I don't understand and I don't know what to try now, can you give me any advice ? 
Regards

**Comment by brad** [comment]
What version of inkscape?

**Comment by emersonmoretto** [comment]
I have exaclty the same issue, Inkscape 1.0..
Any advice??

thank u

**Comment by MaitrePo** [comment]
> What version of inkscape?

SORRY, I missed your message ! It is version 1.0 (4035a4fb49, 2020-05-01)
