### ISSUE TITLE
Plugin no longer seems compatible with inkscape version 1.0

### ISSUE THREAD

**Issue by ghost** [brad/Inkscape-OpenSCAD-DXF-Export#22]
When trying to export from inkscape version 1.0 the following error is shown and no output file is produced.
```
openscad_dxf.py:287: DeprecationWarning: Effect.affect is now `Effect.run()`. The `output` argument has changed.
  OpenSCADDXFEffect().affect()
/home/sly/.config/inkscape/extensions/openscad_dxf/object2path.py:48: DeprecationWarning: Effect.current_layer is now a method in the svg. Use `self.svg.get_current_layer()` instead.
  for node in self.current_layer.iterdescendants():
Traceback (most recent call last):
  File "openscad_dxf.py", line 287, in <module>
    OpenSCADDXFEffect().affect()
  File "/usr/share/inkscape/extensions/inkex/deprecated.py", line 180, in affect
    return self.run(args=args)
  File "/usr/share/inkscape/extensions/inkex/base.py", line 123, in run
    self.save_raw(self.effect())
  File "openscad_dxf.py", line 158, in effect
    object2path.ObjectToPath.effect(self)
  File "/home/sly/.config/inkscape/extensions/openscad_dxf/object2path.py", line 51, in effect
    self.call_inkscape("ObjectToPath", objects)
  File "/home/sly/.config/inkscape/extensions/openscad_dxf/inkinkex.py", line 165, in call_inkscape
    self.parse(tmp)
AttributeError: 'OpenSCADDXFEffect' object has no attribute 'parse'
```
I'm running the latest version of the plugin with Inkscape 1.0 on Arch Linux.

**Comment by mennucc** [comment]
Let me add that recent openscad can read SVG files (with some limitations)

**Comment by PL1-Arcade** [comment]
Inkscape now has native support for exporting DXF files usable by OpenSCAD.
(Tested w. Inkscape v1.4.4. and OpenSCAD 2021.01 on Ubuntu 26.04)
- File -- Save As... (brings up the Save As window)
- Use pulldown menu in the lower right of window to change file type from "Guess from extension" to "Desktop Cutting Plotter (AutoCAD DXF R14)"
- Click on the "Save" button. (brings up an options window)
- Select "Flatten Beziers" then click on the "OK" button.

Scott
