### ISSUE TITLE
Getting a python error when attempting to save

### ISSUE THREAD

**Issue by DeflateAwning** [brad/Inkscape-OpenSCAD-DXF-Export#4]
When I go to save, I get the following error

``` python
Traceback (most recent call last):
  File "openscad_dxf.py", line 271, in <module>
    OpenSCADDXFEffect().affect()
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex.py", line 265, in affect
    self.getposinlayer()
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex.py", line 207, in getposinlayer
    x = self.unittouu( xattr[0] + 'px' )
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex.py", line 351, in unittouu
    return retval * (self.__uuconv[u.string[u.start():u.end()]] / self.__uuconv[self.getDocumentUnit()])
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex.py", line 304, in getDocumentUnit
    p = param.match(svgwidth)
TypeError: expected string or buffer
```

Can anyone help me figure it out?

**Comment by brad** [comment]
@ThePiGuy Can you attach a svg which causes the issue? Also, please post your python and inkscape version.

**Comment by su-v** [comment]
This is a known upstream regression in Inkscape 0.91 (in inkex.py's `Effect()` class) if running a python-based script extension in documents which omit the `width` attribute of the root `<svg>` element: 
- [Bug #1463623 “Error trying to save Optimized SVG (no 'width' attribute for SVGRoot)”](https://bugs.launchpad.net/inkscape/+bug/1463623)

The upstream regression also affects with documents which omit the `height` attribute of the root `<svg>` element; this is tracked separately:
- [Bug #1461346 “getposinlayer fails if height attribute is missing”](https://bugs.launchpad.net/inkscape/+bug/1461346)

Both regressions will be fixed in the next Inkscape release.
