### ISSUE TITLE
Error: Filename or extension is too long

### ISSUE THREAD

**Issue by alexander233** [brad/Inkscape-OpenSCAD-DXF-Export#8]
Hi, when I run your extension, I get the following error (My current version of Inkscape is 0.91 and I am running it on Windows 7 / 64 bit): 

```
Traceback (most recent call last):
  File "openscad_dxf.py", line 287, in <module>
    OpenSCADDXFEffect().affect()
  File "C:\Program Files\Inkscape\share\extensions\inkex.py", line 268, in affect
    self.effect()
  File "openscad_dxf.py", line 158, in effect
    object2path.ObjectToPath.effect(self)
  File "C:\Program Files\Inkscape\share\extensions\openscad_dxf\object2path.py", line 51, in effect
    self.call_inkscape("ObjectToPath", objects)
  File "C:\Program Files\Inkscape\share\extensions\openscad_dxf\inkinkex.py", line 159, in call_inkscape
    p = Popen(cmd, shell=True, stdout=PIPE, stderr=PIPE)
  File "C:\Program Files\Inkscape\python\Lib\subprocess.py", line 633, in __init__
    errread, errwrite)
  File "C:\Program Files\Inkscape\python\Lib\subprocess.py", line 842, in _execute_child
    startupinfo)
WindowsError: [Error 206] The filename or extension is too long
```

**Comment by carlodri** [comment]
Same problem here for me, on Windows 10x64

**Comment by brad** [comment]
@carlodri Is the file name really long? Please try shortening t to see if that helps

**Comment by alexander233** [comment]
This error probably does not refer to the filename of the inkscape file or the output file. Shortening the file name and path did not help.

**Comment by brad** [comment]
Thanks @alexander233 Unfortunately I don't have a windows machine to debug/fix this, so I will have to rely on someone from the community to make a pull request to fix this

**Comment by carlodri** [comment]
could be related to [this](http://www.inkscapeforum.com/viewtopic.php?t=20762&start=25#p86790) point, i.e. a max number of characters allowed in the shell commands

**Comment by brad** [comment]
Thank you Carlo!
